# Generated by Django 5.1.2 on 2024-11-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fasilitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=250)),
                ('gambar', models.ImageField(upload_to='media/images')),
                ('deskripsi', models.TextField()),
            ],
        ),
    ]
