# Generated by Django 5.1.2 on 2024-11-23 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apprumahsakit', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fasilitas',
            new_name='Kamar',
        ),
        migrations.RenameField(
            model_name='kamar',
            old_name='deskripsi',
            new_name='fasilitas',
        ),
    ]
